version: "3.9"

services:
  postgres:
    container_name: postgres_orders
    image: postgres:latest
    ports:
      - "5445:5445"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    networks:
      orders:

networks:
  orders:
    external: true